twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        categoryRepository: "@App\\Repository\\CategoryRepository"
        materialRepository: "@App\\Repository\\MaterialRepository"

when@test:
    twig:
        strict_variables: true


