twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        categoryRepository: "@App\\Repository\\CategoryRepository"
        articleRepository: "@App\\Repository\\ArticleRepository"

when@test:
    twig:
        strict_variables: true


