twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        categoryRepository: "@App\\Repository\\CategoryRepository"
        articleRepository: "@App\\Repository\\ArticleRepository"
        cartService:    "@App\\Controller\\User\\Cart\\CartService"

when@test:
    twig:
        strict_variables: true


